### ISSUE TITLE
fds Nodeの出力仕様についての提案

### ISSUE THREAD

**Issue by hashisan-atBridge** [ia-cloud/node-red-contrib-ia-cloud-fds#20]
現在、fds Nodeは出力メッセージとして、
```
msg = { request: "store",
　　　　dataObject: iaCloudObject
　　　　payload: "data sent"　　　　　// これは私だけしか実装していないかもしれません。
　　　　}
```
を出力する仕様になっていますが、fds Node からのデータオブジェクトをia-cloud格納前になんらかの処理をするケースを想定して、contentData[]のみを取り出すことができるように仕様変更をしたいと思います。

以下の、案について意見をください。
案１：上記の現仕様のpayloadに、contentData[]を出力する。
案２：fds Node の出力を２つにし、出力１は現行仕様のまま、出力２のpayloadにcontentData[]を出力する。

一長一短ですが、両方とも現行のNode・Flowには影響を与えないと思われます。
同じcontentData[]が、payloadと、dataObjectの奥とに重複しますが、案１の方が良いかな・・・

**Comment by ryoichi-obara** [comment]
FDSノードというのは、 ``ia-cloud-cnct`` ノードの出力ということでしょうか？
で、あればpayloadは送ったデータのコピーであってもよい気がします。

**Comment by hashisan-atBridge** [comment]
ここでFDSノードと言ったのはいろいろなセンサNodeのことです。
それらのNodeからia-cloud-cnctへの出力メッセージのことで、現状は、
msg.request : "store"
msg.dataObject : {iaCliudObject}

を出力していますが、{iaCloudObject}の奥のメンバである[contentData]を簡単に
取り出せるようにするため、これに加えて、
msg.payload : [contentData]
を出力するか、出力１に、
msg2.payload : [contentData,]
を出力するかどっちがいいかという話です。

**Comment by ryoichi-obara** [comment]
2という命名が俯瞰的にわかりにくいので、必然的に案1推しです。

ただ、msgが重くなると（特に、本来は持っているデータなのに、データ加工の観点で複数持つと、意味なく重量が2倍になってしまい）エッジに負荷がかかるので、contentDataを取り出すようなconvertノードがあってもいいかなとも思います。

**Comment by hashisan-atBridge** [comment]
2は、命名規則ではなく、Nodeの出力数を２つにして２番目という意味です。Node定義で　outputs:2とすると、Nodeの出力のポッチが２つになるあれです。
２番目の出力のmsg.payloadにcontentDataを出力する仕様です。

でもやっぱり案１ですよね。

**Comment by ryoichi-obara** [comment]
``outputs:2`` なるほど理解しました。
どっちを繋ぐかなど煩雑になりそうなので、どちらかと言われれば案1かなと思います。

**Comment by hashisan-atBridge** [comment]
ia-cloud Node-RED WGにて以下に決定。

msg.request : "store"
msg.dataObject : {iaCliudObject}
msg.payload : [contentData]

msg.payload には、iaCloudObject.objectContent.contentData への参照を代入することで、インスタンスの重複は避けられるため、パフォーマンス上も問題ない。
