### ISSUE TITLE
ヘルプテキストの翻訳に関してのルール

### ISSUE THREAD

**Issue by ryoichi-obara** [ia-cloud/node-red-contrib-ia-cloud-fds#27]
* ノードのhtmlにはヘルプテキストは書かずscriptタグも書かない
* 翻訳されたヘルプテキストは各i18n国際化ディレクトリ配下に置いて記述する

**Comment by hashisan-atBridge** [comment]
ia-cloud Node-RED WGにて議論し上記にて決定。
