### ISSUE TITLE
[PLC-Nodes]cloneしたselectboxは.valでパラメータを代入しても反映されない

### ISSUE THREAD

**Issue by j-yamada** [ia-cloud/node-red-contrib-ia-cloud-fds#29]
PLCノードの設定保存後、設定ノードの設定画面を再表示すると、アドレスのセレクトボックスの表示が空になる。
jQueryの問題で、セレクトボックスをcloneするとval()によるパラメータの代入処理が作用しないのが原因

参考
http://jisakupc-technical.info/programing/jquery/4302/

**Comment by j-yamada** [comment]
現象追記
スクショの赤枠で囲った部分が、一度設定を閉じて再表示すると、空の状態で表示されます
![cloneBug_PLC](https://user-images.githubusercontent.com/39978489/89512348-13b51e00-d80e-11ea-9944-ffe7c4573a9a.jpg)

**Comment by hashisan-atBridge** [comment]
Node-RED1.0.5 では再現せず、1.1.3で再現（必ずしも完全再現ではないが・・・）。
原因は、上記の問題ではなく（val()で値の設定は既に行っている。デバッガーでvalue属性をモニタすると正しく設定されている。）、Locale文字列が取得できていないことが原因。1.0.xから1.1.xへのバージョンアップ時に、なんらかの変更があったと思われる。  
selectのoptionの表示文字列を
```
<option .... ><span data-i18n="xxxx.xx"></span></option>
```
としていたのを、
```
<option ....  data-i18n="xxxx.xx"></option>
```
と変更して対応。
