### ISSUE TITLE
[PLCノード] データの設定のビット情報の出力形式の選択肢が"論理値s"になっている

### ISSUE THREAD

**Issue by ryoichi-obara** [ia-cloud/node-red-contrib-ia-cloud-fds#65]
掲題の通り。

**Comment by hashisan-atBridge** [comment]
has remendied resource file PLC-mitsubishi.json. the value of  key "bool" has been modified as "論理値s"  -->  "論理値"
same as this, the file PLC-mitsubishi-premium.json of the node-red-contrib-ia-cloud-premium repository has been fixed.
